 module.exports = ' /$$$$$$$   /$$$$$$  /$$      /$$ /$$   /$$ /$$$$$$ /$$$$$$$$       /$$      /$$  /$$$$$$  /$$$$$$$  /$$   /$$\r\n'
 + '| $$__  $$ /$$__  $$| $$$    /$$$| $$$ | $$|_  $$_/|__  $$__/      | $$$    /$$$ /$$__  $$| $$__  $$| $$  /$$/\r\n'
+ '| $$  \\ $$| $$  \\ $$| $$$$  /$$$$| $$$$| $$  | $$     | $$         | $$$$  /$$$$| $$  \\ $$| $$  \\ $$| $$ /$$/ \r\n'
+ '| $$  | $$| $$$$$$$$| $$ $$/$$ $$| $$ $$ $$  | $$     | $$         | $$ $$/$$ $$| $$$$$$$$| $$$$$$$/| $$$$$/  \r\n'
+ '| $$  | $$| $$__  $$| $$  $$$| $$| $$  $$$$  | $$     | $$         | $$  $$$| $$| $$__  $$| $$__  $$| $$  $$  \r\n'
+ '| $$  | $$| $$  | $$| $$\\  $ | $$| $$\\  $$$  | $$     | $$         | $$\\  $ | $$| $$  | $$| $$  \\ $$| $$\\  $$ \r\n'
+ '| $$$$$$$/| $$  | $$| $$ \\/  | $$| $$ \\  $$ /$$$$$$   | $$         | $$ \/  | $$| $$  | $$| $$  | $$| $$ \\  $$\r\n'
+ '|_______/ |__/  |__/|__/     |__/|__/  \\__/|______/   |__/         |__/     |__/|__/  |__/|__/  |__/|__/  \\__/\r\n'
+ '\r\n'
+ '\r\n'
+ '                                                                                           .+o:               \r\n'
+ '                                                                                          .dMMm.              \r\n'
+ '                                                                                         .dMMN+               \r\n'
+ '                                                                                        `hMMMo`               \r\n'
+ '                             `````                                                     `yMMMs`                \r\n'
+ '                          `/+++/////-.                                                `oMMMy`                 \r\n'
+ '                         .+o++//+//::/+-                                              oMMMh`                  \r\n'
+ '                        ./+//////::/+/-/+`     `..----.`                             +NMMd.                   \r\n'
+ '                        ``      `-/+::o--.  .+ydmNNMMNNdho-`                        /NMMm-                    \r\n'
+ '                                   `:o:- `:yNMMMMMMMMMMMMMNd+`                     :NMMMd`                    \r\n'
+ '                                     `- .yNMMMMMMMMMMMMMMMMMMd-                   -mMMMMh`                    \r\n'
+ '                                       .hMMMMMMMMMMMMMMMMMMMMMN:                 .dMMNdMd`                    \r\n'
+ '                                       sMMMMMMMMMMMMMMMMMMMMMMMm.               .dMMMo+Mh`                    \r\n'
+ '                               ```   `-NMMMMMMMMMMMMMMMMMMMMMMMM/              `hMMMo +Md`                    \r\n'
+ '                            `/ydmmhohmNMMMMMMMMMMMMMMMMMMMMMMMMM+             `yMMMs` +Mh`                    \r\n'
+ '                          .+dMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN:             oMMMy`  +Mh`                    \r\n'
+ '                        -sNMMMMMMMMMMmdhMMMMMMMMMMMMMMMMMMMMMMMy`            oMMMh`   oMd`                    \r\n'
+ '                     `/hNMMMMMMMMMMMo   oMMMMMMMMMMMMMMMMMMMMMh---++.       .NMMd.    +Mh`                    \r\n'
+ '                   `+mMMMMMMMMMMMNs-     :mMMMMMMMMMMMMMMMMMNs/--o/o+        :o+`     +Mh`                    \r\n'
+ '                 -sNMMMMMMMMMMMMo`         /hNMMMMMMMMMMMMdo.+/:-os:s-                +Mh`                    \r\n'
+ '  /hmmd+`     `/hMMMMMMMMMMMMMMMm:          `/ohmMMMMMNds/:::+os/:y+/:----------:smmmmNMNmmmms:------------`  \r\n'
+ ' +MMMMMMy`  .+mMMMMMMMMMMMMMMMMMMNs`        .MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.  \r\n'
+ ' +MMMMMMN:`sNMMMMMMMMMMMd+/mMMMMMMMm:       -MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.  \r\n'
+ ' .mMMMMMMdyMMMMMMMMMMNy:`  .sMMMMMMMNs`     -MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.  \r\n'
+ '  +MMMMMMMMMMMMMMMMms-       /mMMMMMMMd:    -MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.  \r\n'
+ '  `dMMMMMMMMMMMMMMN:          .yMMMMMMMNs`  -MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.  \r\n'
+ '   /NMMMMMMMMMMMMMN-           `/mMMMMMMMd: -MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.  \r\n'
+ '   `hMMMMMMMMMMMMMN-             .yMMMMMMMNo-MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.  \r\n'
+ '    :NMMMMMMMMMMMMN/.`            `/mMMMMMMm:MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.  \r\n'
+ '    `yMMMMMMMMMMMMMNmmdhso+/:-.`    .yNMMMm+.hhhhhhhhhhhMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.  \r\n'
+ '     -NMMMMMMMMMMMMMMMMMMMMMNNmmdhso+/+oo/.            .NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.  \r\n'
+ '      sMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNmdhyo-         .NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.  \r\n';
